Future/model template json
VisualSystemsCorp/vsc_pdf_template_editor pull request #3
Opened 2022-09-10 10:01 UTC by a5flutter

@dsyrstad we need to agree on classes representing widgets naming: here we have sample for Text , it is named TextPdf. So prefix is PDF. Is it OK, or some other naming convention?

2022-09-10 14:09 UTC, dsyrstad requested changes

2022-09-10 14:09 UTC, dsyrstad commented on vsc_pdf_template_transformer/lib/models/text_pdf.dart
> +      bool? tightBounds = false;
These defaults should be on the constructor since they will be overridden by it. Also `text` should be required (non-nullable). Plus, this task was to just add a single `text` attribute for the Text widget in the template.

2022-09-10 14:09 UTC, dsyrstad commented on vsc_pdf_template_transformer/lib/models/text_style.dart
> +class TextStyle {
I'm concerned about naming confusion here. How about `TplText` and `TplTextStyle` where `Tpl` is an abbreviation for "template".

2022-09-12 08:17 UTC, a5flutter commented on vsc_pdf_template_transformer/lib/models/text_pdf.dart
> +      bool? tightBounds = false;
I think I don't understand what you mean.
Do you mean text should be   # @ required String text ?

2022-09-12 08:36 UTC, a5flutter commented on vsc_pdf_template_transformer/lib/models/text_style.dart
> +class TextStyle {
No problem

2022-09-12 14:04 UTC, closed without merging

2022-09-12 14:05 UTC, dsyrstad commented
Closing in favor of later PR